# Generated by Django 4.2.13 on 2024-05-17 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_article_author_articleseries_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default/1.jpg', max_length=255, upload_to=main.models.Article.image_upload_to),
        ),
        migrations.AddField(
            model_name='articleseries',
            name='image',
            field=models.ImageField(default='default/1.jpg', max_length=255, upload_to=main.models.ArticleSeries.image_upload_to),
        ),
        migrations.AlterField(
            model_name='articleseries',
            name='author',
            field=models.ForeignKey(default=1, max_length=255, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
