# Generated by Django 4.2.13 on 2024-05-17 05:55

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default/5.jpg', upload_to=user.models.CustomUser.image_upload_to),
        ),
    ]
