# Generated by Django 4.2.13 on 2024-05-17 06:05

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default/5.jpeg', upload_to=user.models.CustomUser.image_upload_to),
        ),
    ]
